name: Check Terraform code

on:
  push:
    paths:
      - '**.tf'
  workflow_dispatch:
    inputs:
      input:
        description: "Manual Execution"
        required: true
        default: "Manual Execution"

jobs:
  check-terraform:
    name: Check Terraform code
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.9.0"

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Format Terraform code
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          severity: HIGH,CRITICAL
          limit-severities-for-sarif: true
          trivyignores: .trivyignore
